"""Deterministic answer-pointer catalogue: the judge selects IDs, never rewrites quotes."""
from __future__ import annotations

import json


def evidence_catalogue(answer_text: str) -> tuple[dict[str, str], dict[str, str]]:
    """Return ID -> exact serialized leaf excerpt and ID -> JSON Pointer.

    All strings/numbers/booleans/nulls remain in the original answer. Pointer
    labels are mechanically derived, so neither clinical facts nor evidence
    wording are generated by this helper.
    """
    def bad_constant(value):
        raise ValueError("Candidate answer contains a non-JSON numeric constant")
    answer = json.loads(answer_text, parse_constant=bad_constant)
    if not isinstance(answer, dict):
        raise ValueError("An evidence catalogue requires a structured answer object")
    texts, pointers = {}, {}

    def visit(value, path):
        if isinstance(value, dict):
            for key in sorted(value):
                visit(value[key], path + "/" + key.replace("~", "~0").replace("/", "~1"))
        elif isinstance(value, list):
            for index, item in enumerate(value):visit(item, path + "/" + str(index))
        else:
            serialized = json.dumps(value, ensure_ascii=False)
            excerpt = serialized[1:-1] if isinstance(value, str) else serialized
            if not excerpt:return
            if excerpt not in answer_text:
                raise ValueError("Evidence excerpt is not verbatim in the provided answer")
            key = f"e{len(texts)}"
            texts[key], pointers[key] = excerpt, path

    visit(answer, "")
    return texts, pointers
