"""Item-generation verification report (md) and per-item ledger (JSONL).

For each injected daily event or indicator: does it match the case's recorded facts, does
it leave the gold fields and the offline solvers' conclusions unchanged, and is the
solver-visible text free of answer information. The full ledger is `verify.jsonl` in the
batch directory.

SYNTHETIC, evaluation only; not medical advice.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger("haenv.verify_report")

CHECK_ZH = {
    "in_aux_whitelist": "name is in the auxiliary-signal whitelist",
    "not_clinical_domain_signal": "name doesn't collide with this disease's clinical-domain signals",
    "device_backed": "backed by a device declared in raw_case",
    "values_in_physio_range": "every point falls within the physiological range",
    "baseline_matches_raw_facts": "baseline matches this patient's actual facts",
    "cadence_matches_density": "sampling cadence matches the event density",
    "pre_T_visible": "enough points visible at ≤T",
    "not_driver_or_comorbid_proxy": "not a proxy for the true driver/comorbidity",
    "neutral_across_reversal": "no drift across the reversal point",
    "neutral_across_T": "no drift across index-time T",
    "has_points": "non-empty series",
    "timing_le_T": "timestamp ≤T",
    "timing_nonneg": "timestamp is valid",
    "context_non_attributive": "context carries no attributive wording",
    "no_answer_words": "no answer words",
    "traceable_to_raw_case": "traceable to raw_case's symptom table",
    "plausible_for_profile": "plausible for this patient's profile",
    "no_collision_with_real_symptom": "not on the same day as a real symptom",
    "no_duplicate_topic": "not a semantic duplicate of another event in the same case",
    "not_red_flag_symptom": "not a red-flag symptom (creates no missed-diagnosis trap)",
    "has_text": "event text is non-empty",
    "outcome_label_unchanged": "outcome label unchanged",
    "gold_drivers_unchanged": "gold drivers unchanged",
    "label_rule_unchanged": "labeling rule unchanged",
    # Despite the `_core_` in its name, the check compares the entire adjudication
    # object minus the ledger keys (default-deny).
    "adjudication_core_unchanged": "adjudication gold fields unchanged (including ddx / artifact_flags)",
    "reversal_points_unchanged": "reversal points unchanged",
    "conclusion_same:baseline_slope": "baseline_slope conclusion unchanged",
    "conclusion_same:robust_ref": "robust_ref conclusion unchanged",
    "benign_spread_uniform": "benign events spread uniformly over time",
    "solver_text_no_answer_info": "solver-visible text has no answer information",
}


def _mark(ok: bool) -> str:
    return "✅" if ok else "❌"


def write_jsonl(job, reports: list[dict]) -> Path:
    """Per-item ledger: one line per case with every item and check, in the batch directory."""
    p = job.verify_results_file
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        for rep in reports:
            f.write(json.dumps(rep, ensure_ascii=False) + "\n")
    log.info("[verify_report] per-item ledger -> %s (%d case)", p, len(reports))
    return p


def render(job, audits: list[dict], reports: list[dict], jsonl: Path) -> str:
    ts = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M")
    emitted = [a for a in audits if a.get("emitted")]
    n_items = sum(r.get("n_items", 0) for r in reports)
    n_bad = sum(r.get("n_bad_items", 0) for r in reports)
    n_drop = sum(len(a.get("event_dropped") or []) for a in audits)
    leaky = [r for r in reports if not r["solver_text"]["ok"]]
    failed_cases = [r for r in reports if not r["ok"]]

    L: list[str] = []
    L.append(f"# Item Generation Verification Report — {job.job_id}({job.task_type})\n")
    L.append(f"> Auto-generated by `haenv verify` · {ts} · **eval batch `{job.batch}`**\n>\n"
             f"> Pipeline: raw_case + hidden control variables → hidden-variable premise check → "
             f"conditional generation (GV-1) → **daily event/indicator injection → per-item verification → "
             f"re-inject after dropping failing items** → emission gate.\n>\n"
             f"> Per-item ledger (traceable): `{jsonl.relative_to(job.root)}`. "
             f"SYNTHETIC, evaluation only; not medical advice.\n")
    L.append("---\n")

    # ---------- 1 Overview ----------
    L.append("## 1. Overview\n")
    L.append(f"- Input cases **{len(audits)}** → emitted **{len(emitted)}**; **{n_items}** item checks total, "
             f"**{n_bad}** finally unqualified; **{n_drop}** items dropped and re-injected during the loop.\n")
    cf = job.cases_file
    if cf.is_file():
        L.append(f"- **Saved case body**: `{cf.relative_to(job.root)}`"
                 f"({cf.stat().st_size / 1024:.0f} KB, includes verifier-only ground truth; per-case sha256 "
                 f"recorded in `batch.json`). Evaluation and report re-generation only read this file; "
                 f"they never regenerate the items.\n")
    L.append(f"- Case text handed to the solver: **{len(reports) - len(leaky)}/{len(reports)}** cases scanned "
             f"clean of answer info"
             f"{'(**' + str(len(leaky)) + ' cases hit, see §4**)' if leaky else '(all CLEAN)'}.\n")
    L.append("| case | T | daily indicators | event EV | loop rounds | dropped | item fails | "
             "case-level checks | text scan | emitted |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    by_id = {r["case_id"]: r for r in reports}
    for a in audits:
        r = by_id.get(a["case_id"], {})
        cl = r.get("case_checks") or {}
        L.append(f"| {a['case_id']} | {a.get('T','—')} | {a.get('event_streams','—')} "
                 f"| {a.get('event_evidence','—')} | {a.get('event_rounds','—')} "
                 f"| {len(a.get('event_dropped') or [])} | {r.get('n_bad_items','—')} "
                 f"| {_mark(all(c['ok'] for c in cl.values())) if cl else '—'} "
                 f"| {_mark(r['solver_text']['ok']) if r else '—'} "
                 f"| {'✅' if a.get('emitted') else '⛔'} |")
    L.append("")

    # ---------- 1b What this batch generated: latent control variables + gold truth ----------
    L.append("---\n")
    L.append("## 1b. What this batch generated: latent control variables (verifier-only) and gold-standard truth\n")
    L.append("> **Nothing in this table goes to the solver**: event density/adherence dip/reversal week are "
             "hidden control variables used for generation; outcome label and true driver are the gold used "
             "for scoring. The labeling rule is uniformly `regain ≥ max(5% of weight already lost, 0.75 kg)` on the 7-reading centred rolling median (a gain of 0.75 kg above the low point when less than that was lost) and "
             "`sustained ≥ 8 weeks`, baseline taken at nadir.\n")
    L.append("| case | event density (measure/dosing/symptom/life) | adherence dip | reversal week | "
             "distractor | injected noise | **outcome label (gold)** | **true driver (gold)** |")
    L.append("|---|---|---|---|---|---|---|---|")
    for cs in job.cases:
        a = next((x for x in audits if x["case_id"] == cs.case_id), {})
        ed = cs.latent.get("event_density", {}) or {}
        dens = (f"{ed.get('measure_per_week','—')}/wk · {ed.get('dosing_per_week','—')}/wk · "
                f"{ed.get('symptom_rate','—')} · {ed.get('life_event_rate','—')}")
        nz = ", ".join(f"{n['class']}@wk{n['week']}" for n in cs.noise) or "—"
        L.append(f"| {cs.case_id} | {dens} | {cs.latent.get('adherence_low','—')} "
                 f"| {cs.latent.get('reversal_week','—')} | {cs.distractor_level} | {nz} "
                 f"| `{a.get('outcome_label','not emitted')}` "
                 f"| `{(a.get('gold_drivers') or ['—'])[0]}` |")
    L.append("")

    # ---------- 2 Per-item verification (sample + all failing items) ----------
    n_sample = int(job.sample_cases or 5)
    sample = [r for r in reports[:max(3, min(10, n_sample))]]
    sample_ids = {r["case_id"] for r in sample}
    sample += [r for r in failed_cases if r["case_id"] not in sample_ids]
    L.append("---\n")
    L.append(f"## 2. Per-item verification detail (sampled {len(sample)} cases; all {len(reports)} cases in the JSONL)\n")
    L.append("> Each row = one injected daily indicator or one event EV; each column = one check. "
             "`inherited_*` = items contributed by the upstream injector (kernel distractor) and "
             "re-audited item-by-item at this layer.\n")
    for r in sample:
        L.append(f"### {r['case_id']} (T={r['T']} · true driver `{r['driver']}` · "
                 f"reversal day {r['reversal_day'] if r['reversal_day'] is not None else 'none (maintain)'})\n")
        # 2a Indicator streams
        metrics = [i for i in r["items"] if i["kind"].endswith("metric")]
        if metrics:
            keys = list(dict.fromkeys(k for i in metrics for k in i["checks"]))
            L.append("**Daily indicator streams**:\n")
            L.append("| indicator | kind | " + " | ".join(CHECK_ZH.get(k, k) for k in keys) + " |")
            L.append("|" + "---|" * (len(keys) + 2))
            for i in metrics:
                cells = [_mark(i["checks"][k]["ok"]) if k in i["checks"] else "·" for k in keys]
                L.append(f"| `{i['item']}` | {i['kind']} | " + " | ".join(cells) + " |")
            L.append("")
            det = [f"`{i['item']}`:{i['checks'][k]['detail']}" for i in metrics
                   for k in ("baseline_matches_raw_facts", "neutral_across_T") if k in i["checks"]]
            if det:
                L.append("<details><summary>Expand: measured values behind the baseline/neutrality criteria</summary>\n")
                for d in det:
                    L.append(f"- {d}")
                L.append("\n</details>\n")
        # 2b Events
        evs = [i for i in r["items"] if not i["kind"].endswith("metric")]
        if evs:
            keys = list(dict.fromkeys(k for i in evs for k in i["checks"]))
            L.append("**Event EVs**:\n")
            L.append("| EV | kind | day | text | " + " | ".join(CHECK_ZH.get(k, k) for k in keys) + " |")
            L.append("|" + "---|" * (len(keys) + 4))
            for i in evs:
                cells = [_mark(i["checks"][k]["ok"]) if k in i["checks"] else "·" for k in keys]
                L.append(f"| `{i['item']}` | {i['kind']} | {i.get('day','—')} | {i.get('text','')} | "
                         + " | ".join(cells) + " |")
            L.append("")
        # 2c Case-level
        L.append("**Case-level checks (conclusion invariance / distribution / text)**:\n")
        L.append("| check | result | measured |")
        L.append("|---|---|---|")
        for k, c in r["case_checks"].items():
            L.append(f"| {CHECK_ZH.get(k, k)} | {_mark(c['ok'])} | {c['detail'] or '—'} |")
        L.append("")
        cb, ca = r["conclusion"]["before"], r["conclusion"]["after"]
        L.append("**Before vs after injection (offline deterministic solver)**:\n")
        L.append("| solver | risk/category/driver before | risk/category/driver after | match |")
        L.append("|---|---|---|---|")
        for name in cb:
            same = (cb[name]["risk_category"] == ca[name]["risk_category"]
                    and cb[name]["top_driver"] == ca[name]["top_driver"])
            L.append(f"| {name} | {cb[name]['risk']} / {cb[name]['risk_category']} / "
                     f"{cb[name]['top_driver']} | {ca[name]['risk']} / {ca[name]['risk_category']} / "
                     f"{ca[name]['top_driver']} | {_mark(same)} |")
        L.append("")
        if r.get("skipped"):
            L.append("<details><summary>Expand: this case's excluded/dropped candidates and why</summary>\n")
            for s in r["skipped"]:
                L.append(f"- `{s.get('item')}` — {s.get('reason')}")
            L.append("\n</details>\n")

    # ---------- 3 Items dropped by the generate-verify loop ----------
    L.append("---\n")
    L.append("## 3. What the generate-verify loop dropped (evidence it actually iterated)\n")
    by_id_rep = {r["case_id"]: r for r in reports}
    dropped_any = [(a["case_id"], a.get("event_rounds"), a.get("event_dropped") or [])
                   for a in audits if a.get("event_dropped")]
    if not dropped_any:
        L.append("This batch passed in full on the first round; nothing was dropped.\n")
    else:
        L.append("| case | loop rounds | dropped item | failing check (drop reason) |")
        L.append("|---|---|---|---|")
        for cid, rounds, items in dropped_any:
            why = (by_id_rep.get(cid, {}) or {}).get("drop_reasons") or {}
            for x in items:
                ck = ", ".join(CHECK_ZH.get(k, k) for k in why.get(x, [])) or "—"
                L.append(f"| {cid} | {rounds} | `{x}` | {ck} |")
        L.append("")
        L.append("> Drop reasons are checkable item by item (see each case's \"excluded/dropped candidates\" "
                 "fold-out in §2, and the JSONL). Typical case: the upstream injector injected a wearable "
                 "indicator stream into a patient **who has no such device**, or injected a supposedly "
                 "unrelated sleep/oxygen-saturation stream into an OSA patient — a stream that's "
                 "**isomorphic with the comorbidity**.\n")

    # ---------- 3b Discrete-layer comorbidity coupling ----------
    # `review: pending` rules are flagged here (see `coupling.pending_rules`).
    L.append("---\n")
    L.append("## 3b. Discrete-layer comorbidity coupling (`registry/comorbid_coupling.yaml`)\n")
    # Emitted cases only, the same denominator as the batch gate `check_coupling_observable`.
    _emit = [a for a in audits if a.get("emitted")]
    _cpl = [(a["case_id"], a.get("coupling_fired") or [],
             a.get("coupling_pending_review") or []) for a in _emit]
    _hit = [(c, f, p) for c, f, p in _cpl if f]
    _pend = sorted({r for _c, _f, ps in _cpl for r in ps})
    if not _cpl or all(a.get("coupling_fired") is None for a in audits):
        L.append("> **Not measured** — this batch's audits carry no coupling records. This layer has no "
                 "on/off switch, so its absence can only mean it silently did not run (the batch gate "
                 "`coupling_layer_did_not_run` will fail it).\n")
    elif not _hit:
        L.append(f"This batch's {len(_cpl)} cases include **no matching comorbid patient**, so zero rules "
                 f"fired. This **must not be read as \"the coupling layer passed\"** — the \"layer is "
                 f"broken\" side is caught by the batch gate `coupling_layer_did_not_run`.\n")
    else:
        L.append(f"{len(_hit)}/{len(_cpl)} cases triggered coupling. **It doesn't change day-level values "
                 f"or decide gold** — it only changes \"which path is taken\" (which checks to turn on, "
                 f"which branch of the care pathway); recorded in the Q-side ledger, never in the solver "
                 f"payload.\n")
        L.append("| case | rules fired | pending clinician review |")
        L.append("|---|---|---|")
        for cid, fired, pend in _hit:
            L.append(f"| {cid} | {', '.join(f'`{x}`' for x in fired)} | "
                     f"{', '.join(f'`{x}`' for x in pend) if pend else '—'} |")
        L.append("")
    if _pend:
        L.append(f"> **{len(_pend)} of the rules fired in this batch are `review: pending`**"
                 f"({', '.join(f'`{x}`' for x in _pend)}) — clinician review is not complete. "
                 f"**This section's readings must not go into external material until it is.**\n")

    # ---------- 4 Text leakage ----------
    L.append("---\n")
    L.append("## 4. Answer-information scan of the solver-visible case text (§2 ground-truth isolation)\n")
    L.append("> Scan target = **the case text actually handed to the solver** (`SolverPayload`'s raw JSON, "
             "≤T). Criteria: kernel `leakage_probe` (temporal + structural fields) + ground-truth field "
             "names + Chinese-language answer words + English/Chinese driver names. The `allowed_drivers` "
             "enum in the prompt template lists candidates and does not count as a leak, so it's scanned "
             "separately.\n")
    L.append("| case | payload chars | visible signals | visible evidence | scan result | hits |")
    L.append("|---|---|---|---|---|---|")
    for r in reports:
        t = r["solver_text"]
        L.append(f"| {r['case_id']} | {t['n_chars']} | {t['n_signals']} | {t['n_evidence']} | "
                 f"{'CLEAN' if t['ok'] else 'LEAK'} | {', '.join(t['findings'][:4]) or '—'} |")
    L.append("")
    if failed_cases:
        L.append(f"> **{len(failed_cases)} cases failed verification**"
                 f"({', '.join(r['case_id'] for r in failed_cases)}); they do not count "
                 f"toward the benchmark.\n")
    L.append("---\n")
    L.append(f"*Every item can be audited via `items[].checks` in this case's row of "
             f"`{jsonl.relative_to(job.root)}`.*\n")
    return "\n".join(L)


def write_verify_report(job, audits: list[dict], reports: list[dict]) -> tuple[Path, Path]:
    jsonl = write_jsonl(job, reports)
    md = render(job, audits, reports, jsonl)
    p = job.verify_report_file
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(md, encoding="utf-8")
    log.info("[verify_report] -> %s (%d bytes)", p, len(md))
    return p, jsonl
